server:
  port: 8763

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456a?
    url: jdbc:mysql://10.110.5.114:3306/dv_db_gop?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&

mybatis:
   mapperLocations: classpath:/mapper/*.xml